# Change these first
owner: jamiew0w
repo: status.leech.ie
  
# Add your sites here
sites:
  - name: leech.ie
    url: https://leech.ie
    icon: https://leech.ie/favicon.png
  - name: tracker.leech.ie
    check: "tcp-ping"
    url: t1.leech.ie
    port: 4747
    icon: https://leech.ie/favicon.png

assignees:
  - jamiew0w
workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 * * * *"
  updates: "0 * * * *"
  uptime: "* * * * *"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.leech.ie
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.leech.ie
  theme: "dark"

i18n:
  footer: <a href="https://leech.ie" target="_blank">leech.ie</a>

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
