# Change these first
owner: jamiew0w
repo: status.leech.ie
  
# Add your sites here
sites:
  - name: leech.ie
    url: https://leech.ie
    icon: https://leech.ie/favicon.png
  - name: t1.leech.ie
    url: http://t1.leech.ie:1338
    expectedStatusCodes:
      - 404
    icon: https://leech.ie/favicon.png
  - name: t2.leech.ie
    url: http://t2.leech.ie:1338
    expectedStatusCodes:
      - 404
    icon: https://leech.ie/favicon.png
  - name: t3.leech.ie
    url: http://t3.leech.ie:1338
    expectedStatusCodes:
      - 404
    icon: https://leech.ie/favicon.png
  - name: Broken Site
    url: https://thissitedoesnotexist.com

assignees:
  - jamiew0w

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.leech.ie
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.leech.ie
  theme: "dark"

i18n:
  footer: <a href="https://leech.ie" target="_blank">leech.ie</a>

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
